version: '3.9'

services:

  client : 
    image : client
    build : ./client
    ports : 
      - "3000:3000" 
  
  server : 
    image : server
    build : ./server
    ports : 
      - "3001:3001"